spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: "8/PIgKIm4uQUpSGNJ7eOYLVhHIme4COVZyY+By+WE7I="  # 256位密钥
  expiration-millis: 86400000  # 一天